# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dinal/image_processing/image_processing.srcs/sources_1/ip/output_buffer/output_buffer.xci
# IP: The module: 'output_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dinal/image_processing/image_processing.gen/sources_1/ip/output_buffer/output_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dinal/image_processing/image_processing.gen/sources_1/ip/output_buffer/output_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/dinal/image_processing/image_processing.srcs/sources_1/ip/output_buffer/output_buffer.xci
# IP: The module: 'output_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dinal/image_processing/image_processing.gen/sources_1/ip/output_buffer/output_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dinal/image_processing/image_processing.gen/sources_1/ip/output_buffer/output_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
